/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SimRouteImport } from './routes/sim'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevLmPhysicsRouteImport } from './routes/dev.lm-physics'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SimRoute = SimRouteImport.update({
  id: '/sim',
  path: '/sim',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLmPhysicsRoute = DevLmPhysicsRouteImport.update({
  id: '/dev/lm-physics',
  path: '/dev/lm-physics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capture': typeof CaptureRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRoute
  '/sim': typeof SimRoute
  '/sources': typeof SourcesRoute
  '/dev/lm-physics': typeof DevLmPhysicsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capture': typeof CaptureRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRoute
  '/sim': typeof SimRoute
  '/sources': typeof SourcesRoute
  '/dev/lm-physics': typeof DevLmPhysicsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capture': typeof CaptureRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRoute
  '/sim': typeof SimRoute
  '/sources': typeof SourcesRoute
  '/dev/lm-physics': typeof DevLmPhysicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/capture'
    | '/explore'
    | '/learn'
    | '/sim'
    | '/sources'
    | '/dev/lm-physics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/capture'
    | '/explore'
    | '/learn'
    | '/sim'
    | '/sources'
    | '/dev/lm-physics'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/capture'
    | '/explore'
    | '/learn'
    | '/sim'
    | '/sources'
    | '/dev/lm-physics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaptureRoute: typeof CaptureRoute
  ExploreRoute: typeof ExploreRoute
  LearnRoute: typeof LearnRoute
  SimRoute: typeof SimRoute
  SourcesRoute: typeof SourcesRoute
  DevLmPhysicsRoute: typeof DevLmPhysicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim': {
      id: '/sim'
      path: '/sim'
      fullPath: '/sim'
      preLoaderRoute: typeof SimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/lm-physics': {
      id: '/dev/lm-physics'
      path: '/dev/lm-physics'
      fullPath: '/dev/lm-physics'
      preLoaderRoute: typeof DevLmPhysicsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaptureRoute: CaptureRoute,
  ExploreRoute: ExploreRoute,
  LearnRoute: LearnRoute,
  SimRoute: SimRoute,
  SourcesRoute: SourcesRoute,
  DevLmPhysicsRoute: DevLmPhysicsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
